// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Properties.Data;

#nullable disable

namespace Properties.Data.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    [Migration("20260204193049_SmallFixInPropertyMediaTable")]
    partial class SmallFixInPropertyMediaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("properties")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Properties.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Locations", "properties");
                });

            modelBuilder.Entity("Properties.Domain.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Managers", "properties");
                });

            modelBuilder.Entity("Properties.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ApplicationFee")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<double>("AverageRating")
                        .HasPrecision(1, 1)
                        .HasColumnType("double precision");

                    b.Property<double>("Baths")
                        .HasPrecision(2, 1)
                        .HasColumnType("double precision");

                    b.Property<int>("Beds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Highlights")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsParkingIncluded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPetsAllowed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManagerAssignedId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("NumberOfReviews")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PricePerMonth")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid>("PropertyLocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SecurityDeposit")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<double>("SquareFeet")
                        .HasPrecision(7, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagerAssignedId");

                    b.HasIndex("PropertyLocationId");

                    b.ToTable("Properties", "properties");
                });

            modelBuilder.Entity("Properties.Domain.PropertyMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PhotoKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyMedia", "properties");
                });

            modelBuilder.Entity("Properties.Domain.Property", b =>
                {
                    b.HasOne("Properties.Domain.Manager", "ManagerAssigned")
                        .WithMany()
                        .HasForeignKey("ManagerAssignedId");

                    b.HasOne("Properties.Domain.Location", "PropertyLocation")
                        .WithMany()
                        .HasForeignKey("PropertyLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerAssigned");

                    b.Navigation("PropertyLocation");
                });

            modelBuilder.Entity("Properties.Domain.PropertyMedia", b =>
                {
                    b.HasOne("Properties.Domain.Property", null)
                        .WithMany("PhotoKeys")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Properties.Domain.Property", b =>
                {
                    b.Navigation("PhotoKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
